### ISSUE TITLE
Навести порядок в наименованиях (ТА)

### ISSUE THREAD

**Issue by apoddubny** [SEAFTeam/seaf-dzo#39]
```
# Базовые типы Технологических компонентов
seaf.ta.components.base.types:
  title: Тип технологического компонента
  type: string
  enum: [СХД аппаратные, Серверы аппаратные, Серверы виртуальные, Сетевое устройство, Развёртывание, POD, Контейнер, Образ, Клиентское устройство, Офис]

seaf.ta.services.base.types:
  title: Тип технологического сервиса
  type: string
  enum: [Регион, Зона доступности, ЦОД, СХД программные, Объектные хранилища, Вычислительный сервис, Кластеризация, Виртуализация, Контейнеризация, Сеть LAN, Сеть WAN, Сеть DMZ, Сеть Каналы передачи данных, Система резервного копирования, Система мониторинга, Лицензии]

```
Тут все варианты по идее должны быть в единственном числе. Почему **Серверы виртуальные**, и рядом **Образ**?  Возможно добавить еще одно поле кол-во (например для лицензий)
Еще неплохо было бы привести README.MD в соотвествие с этим списком.
